const workouts={
A:[
{id:"pushup",name:"Push-Ups on Parallettes",target:"6–15",min:6,max:15,cue:"Tělo drž v jedné linii a hrudník spouštěj mezi madla.",how:"Opři se o parallettes, zpevni celé tělo, kontrolovaně klesni dolů a vytlač se zpět.",watch:"Nenech propadnout boky a lokty zbytečně nevystrkuj do stran.",harder:"Feet-elevated nebo band-resisted push-ups"},
{id:"dbrow",name:"One-Arm Dumbbell Row",target:"8–15 / ruka",min:8,max:15,cue:"Loket táhni směrem k boku a trup drž stabilní.",how:"Lehce se předkloň, jednou rukou se zapři a činku přitáhni k boku.",watch:"Nekrč rameno k uchu a neházej činkou švihem.",harder:"Pomalejší spouštění / pauza nahoře"},
{id:"bss",name:"Bulgarian Split Squat",target:"8–15 / noha",min:8,max:15,cue:"Pracuje hlavně přední noha, zadní je opřená za tebou.",how:"Kontrolovaně klesni dolů a vytlač se přes přední nohu zpět nahoru.",watch:"Neskákej zespodu a nenech koleno padat dovnitř.",harder:"Obě 9kg činky / pomalejší tempo / pauza dole"},
{id:"rdl",name:"Dumbbell Romanian Deadlift",target:"10–20",min:10,max:20,cue:"Posílej boky dozadu a činky drž blízko nohou.",how:"Kolena lehce povol, ohni se v kyčlích, ucítíš tah v hamstringách a vrať se do stoje.",watch:"Nekulať záda a nedělej z pohybu dřep.",harder:"Single-leg RDL nebo činky + resistance band"},
{id:"pike",name:"Pike Push-Up",target:"5–12",min:5,max:12,cue:"Boky drž vysoko, hlava jde dopředu a dolů mezi ruce.",how:"Začni v obráceném V, pokrč lokty, spusť hlavu k zemi a vytlač se zpět.",watch:"Nedělej z toho klasický klik — boky musí zůstat vysoko.",harder:"Feet-elevated pike push-up"},
{id:"lsit",name:"Tuck L-Sit",target:"10–30 s",min:10,max:30,cue:"Tlač parallettes dolů, kolena zvedni k hrudníku a ramena drž od uší.",how:"Zvedni se na propnutých pažích a drž obě kolena přitažená před tělem.",watch:"Nepropadej se v ramenou a neroztahuj kolena zbytečně do stran.",harder:"One-leg L-sit → advanced tuck → full L-sit",timed:true}],
B:[
{id:"bandpushup",name:"Push-Ups / Band-Resisted Push-Ups",target:"6–15",min:6,max:15,cue:"Stejný pohyb jako u kliku, guma přidá odpor při vytlačení.",how:"Veď gumu přes horní část zad, konce drž pod dlaněmi a udělej klasický klik.",watch:"Drž celé tělo pevné a nevytlačuj se nejdřív hrudníkem a až potom boky.",harder:"Silnější guma / feet elevated"},
{id:"bandrow",name:"Band Row / One-Arm DB Row",target:"10–20",min:10,max:20,cue:"Táhni lokty dozadu a nahoře stáhni lopatky.",how:"Gumu bezpečně ukotvi, přitáhni ji k trupu a návrat kontroluj.",watch:"Nenech ramena padat dopředu a nehoupej trupem.",harder:"Silnější guma / delší pauza v kontrakci"},
{id:"lunge",name:"Reverse Lunges with Dumbbells",target:"8–15 / noha",min:8,max:15,cue:"Udělej krok dozadu, klesni dolů a vrať se přes přední nohu.",how:"Činky drž podél těla a nohy můžeš střídat nebo odjet jednu stranu najednou.",watch:"Nedělej příliš krátký krok a hlídej stabilitu předního kolena.",harder:"Obě 9kg činky / deficit reverse lunge"},
{id:"bridge",name:"Single-Leg Glute Bridge + Dumbbell",target:"10–20 / noha",min:10,max:20,cue:"Tlač přes patu a nahoře vědomě zatni hýždi.",how:"Lež na zádech, jednu nohu nech na zemi, činku polož na pánev a zvedej boky.",watch:"Nahoře se neprohýbej v bedrech.",harder:"Pauza nahoře / elevated single-leg bridge"},
{id:"pullapart",name:"Band Pull-Aparts",target:"12–25",min:12,max:25,cue:"Paže téměř propnuté, gumu roztahuj před hrudníkem.",how:"Drž gumu před sebou a roztáhni ji do stran, dokud se lopatky nestáhnou k sobě.",watch:"Nezvedej ramena k uším a návrat nepusť nekontrolovaně.",harder:"Silnější guma / pomalejší návrat"},
{id:"sideplank",name:"Side Plank",target:"20–45 s / strana",min:20,max:45,cue:"Loket je pod ramenem, boky nahoře a tělo v jedné linii.",how:"Opři se o předloktí a hranu chodidla, zvedni boky a drž pevný střed těla.",watch:"Nenech boky padat dolů ani hrudník rotovat k zemi.",harder:"Star side plank / delší výdrž",timed:true}]};

const state={settings:JSON.parse(localStorage.getItem("hw2-settings")||"null")||{startDate:new Date().toISOString().slice(0,10),rest:75},history:JSON.parse(localStorage.getItem("hw2-history")||"[]"),weights:JSON.parse(localStorage.getItem("hw2-weights")||"[]"),active:null,timer:{remaining:75,running:false,interval:null},calendarDate:new Date()};
function save(){localStorage.setItem("hw2-settings",JSON.stringify(state.settings));localStorage.setItem("hw2-history",JSON.stringify(state.history));localStorage.setItem("hw2-weights",JSON.stringify(state.weights));}
function programWeek(){const a=new Date(state.settings.startDate+"T00:00:00"),now=new Date(),days=Math.max(0,Math.floor((now-a)/86400000));return Math.min(6,Math.floor(days/7)+1)}
function recommendedFrequency(){return programWeek()<=2?2:3} function nextWorkout(){if(!state.history.length)return"A";return state.history[0].workout==="A"?"B":"A"}
function fmtTime(s){return `${Math.floor(s/60).toString().padStart(2,"0")}:${(s%60).toString().padStart(2,"0")}`} function dateLabel(x){return new Intl.DateTimeFormat("cs-CZ",{day:"numeric",month:"short",year:"numeric"}).format(new Date(x))} function elapsed(){return state.active?fmtTime(Math.floor((Date.now()-state.active.startedAt)/1000)):"00:00"}
function renderToday(){const w=nextWorkout();document.getElementById('workout-title').textContent=`Doporučeno: Workout ${w}`;document.getElementById('workout-subtitle').textContent=`Full body · ${workouts[w].length} cviků · přibližně 20–30 min`;document.getElementById('phase-pill').textContent=`Týden ${programWeek()} · cíl ${recommendedFrequency()}× týdně`;document.getElementById('start-recommended').textContent=`Start Workout ${w}`}
function findLastExercise(id){for(const h of state.history){const x=h.exercises.find(e=>e.id===id);if(x)return x}return null}
function progressSuggestion(ex,rec){const reps=rec.reps.filter(v=>v!==null);return reps.length===2&&reps.every(v=>v>=ex.max)&&['2','3+'].includes(rec.rir)?`<div class="suggestion">↑ Vypadá to lehce. Příště zvaž těžší variantu: <b>${ex.harder}</b>.</div>`:''}
function renderActive(){const box=document.getElementById('active-workout');if(!state.active){box.classList.add('hidden');return}box.classList.remove('hidden');document.getElementById('next-card').classList.add('hidden');document.querySelector('.hero-card').classList.add('hidden');document.getElementById('session-name').textContent=`Workout ${state.active.workout}`;const list=document.getElementById('exercise-list');list.innerHTML='';workouts[state.active.workout].forEach((ex,i)=>{const r=state.active.exercises[i],prior=findLastExercise(ex.id),card=document.createElement('article');card.className='exercise-card';card.innerHTML=`<div class="exercise-head"><div><div class="exercise-title">${ex.name}</div><div class="target">Cíl: 2× ${ex.target}${prior?` · minule ${prior.reps.join(' / ')}`:''}</div></div><div class="pill">${i+1}/${workouts[state.active.workout].length}</div></div><div class="demo-wrap"><div class="demo-canvas">${demoSVG(ex.id)}</div><div class="demo-note"><strong>Ukázka pohybu</strong><small>${ex.cue}</small></div></div><div class="howto"><div class="how-line"><b>Jak na to:</b> ${ex.how}</div><div class="how-line"><b>Pozor na:</b> ${ex.watch}</div></div><div class="sets">${[0,1].map(si=>`<div class="set-row"><div class="set-num">SÉRIE ${si+1}</div><input class="rep-input" data-ex="${i}" data-set="${si}" type="number" min="0" max="99" placeholder="${ex.timed?'sekundy':'reps'}" value="${r.reps[si]??''}"><button class="done-set" data-done="${i}:${si}">✓</button></div>`).join('')}</div><div class="rir-block"><div class="rir-label">RIR po poslední sérii</div><div class="rir-buttons">${['0','1','2','3+'].map(v=>`<button class="rir-btn ${r.rir===v?'selected':''}" data-rir="${i}:${v}">${v}</button>`).join('')}</div></div>${progressSuggestion(ex,r)}`;list.appendChild(card)});document.querySelectorAll('.rep-input').forEach(x=>x.addEventListener('input',e=>{const i=+e.target.dataset.ex,s=+e.target.dataset.set;state.active.exercises[i].reps[s]=e.target.value===''?null:+e.target.value}));document.querySelectorAll('[data-done]').forEach(b=>b.addEventListener('click',e=>{const [i,s]=e.currentTarget.dataset.done.split(':').map(Number),inp=document.querySelector(`.rep-input[data-ex="${i}"][data-set="${s}"]`);if(inp.value===''){inp.focus();return}startRestTimer()}));document.querySelectorAll('[data-rir]').forEach(b=>b.addEventListener('click',e=>{const [i,v]=e.currentTarget.dataset.rir.split(':');state.active.exercises[+i].rir=v;renderActive()}))}
function startWorkout(w=nextWorkout()){state.active={workout:w,startedAt:Date.now(),exercises:workouts[w].map(ex=>({id:ex.id,name:ex.name,reps:[null,null],rir:null}))};renderActive();if(!window.sessionClock)window.sessionClock=setInterval(()=>{if(state.active)document.getElementById('session-time').textContent=elapsed()},1000)}
function finishWorkout(){if(!state.active||!state.active.exercises.some(e=>e.reps.some(v=>v!==null)))return;state.history.unshift({workout:state.active.workout,date:new Date().toISOString(),durationSec:Math.floor((Date.now()-state.active.startedAt)/1000),exercises:state.active.exercises});state.active=null;save();document.querySelector('.hero-card').classList.remove('hidden');document.getElementById('next-card').classList.remove('hidden');renderAll()}
function cancelWorkout(){state.active=null;document.querySelector('.hero-card').classList.remove('hidden');document.getElementById('next-card').classList.remove('hidden');renderActive()}
function startRestTimer(){clearInterval(state.timer.interval);state.timer.remaining=+state.settings.rest;state.timer.running=true;document.getElementById('timer-sheet').classList.remove('hidden');tickTimer();state.timer.interval=setInterval(()=>{if(state.timer.running&&state.timer.remaining>0){state.timer.remaining--;tickTimer()}},1000)} function tickTimer(){document.getElementById('timer-value').textContent=fmtTime(state.timer.remaining);document.getElementById('timer-toggle').textContent=state.timer.running?'Pauza':'Pokračovat'}
function renderHistory(){const box=document.getElementById('history-list');box.innerHTML=state.history.length?state.history.slice(0,20).map(h=>`<div class="history-item"><div class="history-top"><strong>Workout ${h.workout}</strong><span class="history-date">${dateLabel(h.date)} · ${fmtTime(h.durationSec)}</span></div><div class="history-summary">${h.exercises.map(e=>`${e.name}: ${e.reps.map(v=>v??'–').join(' / ')}${e.rir?` · RIR ${e.rir}`:''}`).join('<br>')}</div></div>`).join(''):'<div class="muted">První workout se tu objeví po dokončení.</div>'}
function renderPlan(){document.getElementById('plan-list').innerHTML=['A','B'].map(w=>`<div class="plan-card plan-workout"><h2>Workout ${w}</h2>${workouts[w].map(ex=>`<div class="plan-ex"><div>${ex.name}</div><small>2× ${ex.target}</small></div>`).join('')}</div>`).join('')}
function renderWeights(){const box=document.getElementById('weight-summary'),chart=document.getElementById('weight-chart');if(!state.weights.length){box.textContent='Zatím bez záznamu.';chart.innerHTML='';return}const latest=state.weights.at(-1),first=state.weights[0],d=(latest.value-first.value).toFixed(1);box.textContent=`Aktuálně ${latest.value.toFixed(1)} kg · změna ${d>0?'+':''}${d} kg`;const data=state.weights.slice(-20);if(data.length<2){chart.innerHTML='';return}const vals=data.map(x=>x.value),min=Math.min(...vals)-.5,max=Math.max(...vals)+.5,pts=data.map((x,i)=>`${10+i*(280/(data.length-1))},${105-((x.value-min)/(max-min))*90}`).join(' ');chart.innerHTML=`<svg viewBox="0 0 300 120"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function startOfWeek(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return x}
function renderWeekSummary(){const start=startOfWeek(),end=new Date(start);end.setDate(end.getDate()+7);const count=state.history.filter(h=>{const d=new Date(h.date);return d>=start&&d<end}).length,target=recommendedFrequency();document.getElementById('week-summary').innerHTML=`<div><div class="week-big">${count}/${target}</div><div class="muted">workoutů tento týden</div></div><div class="pill">${count>=target?'Splněno ✓':`${Math.max(0,target-count)} zbývá`}</div>`}
function renderCalendar(){const y=state.calendarDate.getFullYear(),m=state.calendarDate.getMonth();document.getElementById('calendar-title').textContent=new Intl.DateTimeFormat('cs-CZ',{month:'long',year:'numeric'}).format(new Date(y,m,1));const grid=document.getElementById('calendar-grid');grid.innerHTML='';const first=new Date(y,m,1),offset=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),today=new Date();for(let i=0;i<offset;i++)grid.insertAdjacentHTML('beforeend','<div class="cal-day empty"></div>');for(let day=1;day<=days;day++){const ds=new Date(y,m,day),matches=state.history.filter(h=>{const d=new Date(h.date);return d.getFullYear()===y&&d.getMonth()===m&&d.getDate()===day});const badges=matches.slice(0,2).map(h=>`<span class="cal-badge ${h.workout.toLowerCase()}">${h.workout}</span>`).join('');const isToday=ds.toDateString()===today.toDateString();grid.insertAdjacentHTML('beforeend',`<div class="cal-day ${isToday?'today':''}"><span>${day}</span><div class="cal-badges">${badges}</div></div>`)}}
function renderAll(){renderToday();renderActive();renderHistory();renderPlan();renderWeights();renderWeekSummary();renderCalendar()}

function demoSVG(id){const S=`<svg class="demo-svg" viewBox="0 0 320 180" xmlns="http://www.w3.org/2000/svg">`,E='</svg>',F='<line class="floor" x1="12" y1="158" x2="308" y2="158"/>',P='<line class="equip" x1="110" y1="118" x2="110" y2="144"/><line class="equip" x1="145" y1="118" x2="145" y2="144"/><line class="equip" x1="175" y1="118" x2="175" y2="144"/><line class="equip" x1="210" y1="118" x2="210" y2="144"/>';
const D={
pushup:`${S}${F}${P}<g class="person"><circle class="head" r="10"><animate attributeName="cx" values="125;123;125" dur="2.4s" repeatCount="indefinite"/><animate attributeName="cy" values="98;110;98" dur="2.4s" repeatCount="indefinite"/></circle><line x1="135" y1="100" x2="180" y2="110"><animate attributeName="y1" values="100;112;100" dur="2.4s" repeatCount="indefinite"/><animate attributeName="y2" values="110;118;110" dur="2.4s" repeatCount="indefinite"/></line><line x1="180" y1="110" x2="230" y2="128"><animate attributeName="y1" values="110;118;110" dur="2.4s" repeatCount="indefinite"/><animate attributeName="y2" values="128;134;128" dur="2.4s" repeatCount="indefinite"/></line><line x1="145" y1="108" x2="145" y2="118"><animate attributeName="y1" values="108;120;108" dur="2.4s" repeatCount="indefinite"/></line><line x1="175" y1="112" x2="175" y2="118"><animate attributeName="y1" values="112;122;112" dur="2.4s" repeatCount="indefinite"/></line></g>${E}`,
bandpushup:null,
dbrow:`${S}${F}<g class="person"><circle class="head" cx="135" cy="58" r="10"/><line x1="140" y1="68" x2="172" y2="96"/><line x1="172" y1="96" x2="202" y2="142"/><line x1="172" y1="96" x2="165" y2="146"/><line x1="148" y1="80" x2="140" y2="140"/><line x1="164" y1="92" x2="190" y2="116"><animate attributeName="x2" values="190;205;190" dur="2.2s" repeatCount="indefinite"/><animate attributeName="y2" values="116;100;116" dur="2.2s" repeatCount="indefinite"/></line><g class="weight"><line x1="184" y1="112" x2="196" y2="120"><animate attributeName="x1" values="184;199;184" dur="2.2s" repeatCount="indefinite"/><animate attributeName="y1" values="112;96;112" dur="2.2s" repeatCount="indefinite"/><animate attributeName="x2" values="196;211;196" dur="2.2s" repeatCount="indefinite"/><animate attributeName="y2" values="120;104;120" dur="2.2s" repeatCount="indefinite"/></line></g></g>${E}`,
bss:`${S}${F}<line class="equip" x1="228" y1="122" x2="274" y2="122"/><g class="person"><circle class="head" r="10"><animate attributeName="cx" values="155;155;155" dur="2.2s" repeatCount="indefinite"/><animate attributeName="cy" values="58;76;58" dur="2.2s" repeatCount="indefinite"/></circle><line x1="155" y1="70" x2="155" y2="110"><animate attributeName="y1" values="70;88;70" dur="2.2s" repeatCount="indefinite"/><animate attributeName="y2" values="110;128;110" dur="2.2s" repeatCount="indefinite"/></line><line x1="155" y1="110" x2="140" y2="140"><animate attributeName="y1" values="110;128;110" dur="2.2s" repeatCount="indefinite"/></line><line x1="155" y1="110" x2="214" y2="118"><animate attributeName="y1" values="110;128;110" dur="2.2s" repeatCount="indefinite"/></line><line x1="214" y1="118" x2="248" y2="122"/></g>${E}`,
rdl:`${S}${F}<g class="person"><circle class="head" r="10"><animate attributeName="cx" values="165;176;165" dur="2.3s" repeatCount="indefinite"/><animate attributeName="cy" values="55;72;55" dur="2.3s" repeatCount="indefinite"/></circle><line x1="165" y1="67" x2="170" y2="112"><animate attributeName="x1" values="165;176;165" dur="2.3s" repeatCount="indefinite"/><animate attributeName="y1" values="67;84;67" dur="2.3s" repeatCount="indefinite"/><animate attributeName="x2" values="170;190;170" dur="2.3s" repeatCount="indefinite"/></line><line x1="170" y1="112" x2="150" y2="156"/><line x1="170" y1="112" x2="190" y2="156"/><line x1="168" y1="82" x2="145" y2="118"><animate attributeName="x1" values="168;182;168" dur="2.3s" repeatCount="indefinite"/><animate attributeName="y1" values="82;102;82" dur="2.3s" repeatCount="indefinite"/><animate attributeName="x2" values="145;160;145" dur="2.3s" repeatCount="indefinite"/><animate attributeName="y2" values="118;140;118" dur="2.3s" repeatCount="indefinite"/></line><line x1="172" y1="82" x2="198" y2="118"><animate attributeName="x1" values="172;186;172" dur="2.3s" repeatCount="indefinite"/><animate attributeName="y1" values="82;102;82" dur="2.3s" repeatCount="indefinite"/><animate attributeName="x2" values="198;213;198" dur="2.3s" repeatCount="indefinite"/><animate attributeName="y2" values="118;140;118" dur="2.3s" repeatCount="indefinite"/></line><g class="weight"><rect x="137" y="115" width="16" height="8" rx="3"><animate attributeName="x" values="137;152;137" dur="2.3s" repeatCount="indefinite"/><animate attributeName="y" values="115;137;115" dur="2.3s" repeatCount="indefinite"/></rect><rect x="190" y="115" width="16" height="8" rx="3"><animate attributeName="x" values="190;205;190" dur="2.3s" repeatCount="indefinite"/><animate attributeName="y" values="115;137;115" dur="2.3s" repeatCount="indefinite"/></rect></g></g>${E}`,
pike:`${S}${F}<g class="person"><circle class="head" r="10"><animate attributeName="cx" values="145;143;145" dur="2.2s" repeatCount="indefinite"/><animate attributeName="cy" values="110;126;110" dur="2.2s" repeatCount="indefinite"/></circle><line x1="155" y1="110" x2="188" y2="82"><animate attributeName="y1" values="110;126;110" dur="2.2s" repeatCount="indefinite"/></line><line x1="188" y1="82" x2="230" y2="118"/><line x1="155" y1="110" x2="155" y2="145"><animate attributeName="y1" values="110;126;110" dur="2.2s" repeatCount="indefinite"/></line><line x1="188" y1="82" x2="200" y2="145"/></g>${E}`,
lsit:`${S}${F}${P}<g class="person"><circle class="head" cx="160" cy="56" r="10"/><line x1="160" y1="68" x2="160" y2="104"/><line x1="146" y1="80" x2="145" y2="118"/><line x1="174" y1="80" x2="175" y2="118"/><line x1="160" y1="104" x2="143" y2="102"/><line x1="143" y1="102" x2="128" y2="104"/><line x1="160" y1="104" x2="177" y2="102"/><line x1="177" y1="102" x2="192" y2="104"/></g>${E}`,
bandrow:`${S}${F}<line class="equip" x1="45" y1="70" x2="45" y2="150"/><path class="band" d="M45 98 Q90 92 120 104"><animate attributeName="d" values="M45 98 Q90 92 120 104;M45 98 Q95 78 138 88;M45 98 Q90 92 120 104" dur="2.1s" repeatCount="indefinite"/></path><g class="person"><circle class="head" cx="160" cy="74" r="11"/><line x1="160" y1="86" x2="160" y2="122"/><line x1="160" y1="96" x2="120" y2="104"><animate attributeName="x2" values="120;138;120" dur="2.1s" repeatCount="indefinite"/></line><line x1="160" y1="122" x2="142" y2="150"/><line x1="160" y1="122" x2="178" y2="150"/></g>${E}`,
lunge:`${S}${F}<g class="person"><circle class="head" cx="160" r="10"><animate attributeName="cy" values="58;76;58" dur="2.2s" repeatCount="indefinite"/></circle><line x1="160" y1="70" x2="160" y2="110"><animate attributeName="y1" values="70;88;70" dur="2.2s" repeatCount="indefinite"/><animate attributeName="y2" values="110;128;110" dur="2.2s" repeatCount="indefinite"/></line><line x1="160" y1="110" x2="144" y2="140"/><line x1="160" y1="110" x2="202" y2="138"/></g>${E}`,
bridge:`${S}${F}<g class="person"><circle class="head" cx="95" cy="122" r="10"/><line x1="104" y1="120" x2="152" y2="120"><animate attributeName="y1" values="120;90;120" dur="2s" repeatCount="indefinite"/><animate attributeName="y2" values="120;90;120" dur="2s" repeatCount="indefinite"/></line><line x1="152" y1="120" x2="190" y2="122"><animate attributeName="y1" values="120;90;120" dur="2s" repeatCount="indefinite"/></line><line x1="152" y1="120" x2="182" y2="156"><animate attributeName="y1" values="120;90;120" dur="2s" repeatCount="indefinite"/></line></g>${E}`,
pullapart:`${S}${F}<g class="person"><circle class="head" cx="160" cy="55" r="10"/><line x1="160" y1="66" x2="160" y2="110"/><line class="band" x1="130" y1="90" x2="190" y2="90"><animate attributeName="x1" values="130;96;130" dur="2.1s" repeatCount="indefinite"/><animate attributeName="x2" values="190;224;190" dur="2.1s" repeatCount="indefinite"/></line><line x1="160" y1="88" x2="130" y2="90"><animate attributeName="x2" values="130;96;130" dur="2.1s" repeatCount="indefinite"/></line><line x1="160" y1="88" x2="190" y2="90"><animate attributeName="x2" values="190;224;190" dur="2.1s" repeatCount="indefinite"/></line><line x1="160" y1="110" x2="142" y2="150"/><line x1="160" y1="110" x2="178" y2="150"/></g>${E}`,
sideplank:`${S}${F}<g class="person"><circle class="head" cx="122" cy="74" r="9"/><line x1="130" y1="80" x2="205" y2="110"><animate attributeName="y1" values="80;72;80" dur="2s" repeatCount="indefinite"/><animate attributeName="y2" values="110;102;110" dur="2s" repeatCount="indefinite"/></line><line x1="152" y1="88" x2="135" y2="128"/><line x1="205" y1="110" x2="234" y2="90"/><line x1="205" y1="110" x2="232" y2="132"/></g>${E}`};D.bandpushup=D.pushup.replace('</svg>','<path class="band" d="M135 98 Q180 82 220 124"/></svg>');return D[id]||`${S}${F}${E}`}

document.getElementById('start-recommended').addEventListener('click',()=>startWorkout());document.querySelectorAll('.start-specific').forEach(b=>b.addEventListener('click',()=>startWorkout(b.dataset.workout)));document.getElementById('finish-workout').addEventListener('click',finishWorkout);document.getElementById('cancel-workout').addEventListener('click',cancelWorkout);document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(t.dataset.view).classList.add('active');document.getElementById('page-title').textContent=t.textContent;if(t.dataset.view==='progress-view'){renderCalendar();renderWeekSummary()}}));document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>{state.timer.remaining=Math.max(0,state.timer.remaining + +b.dataset.add);tickTimer()}));document.getElementById('timer-toggle').addEventListener('click',()=>{state.timer.running=!state.timer.running;tickTimer()});document.getElementById('timer-close').addEventListener('click',()=>document.getElementById('timer-sheet').classList.add('hidden'));document.getElementById('settings-btn').addEventListener('click',()=>{document.getElementById('start-date').value=state.settings.startDate;document.getElementById('rest-seconds').value=state.settings.rest;document.getElementById('settings-sheet').classList.remove('hidden')});document.getElementById('settings-close').addEventListener('click',()=>document.getElementById('settings-sheet').classList.add('hidden'));document.getElementById('save-settings').addEventListener('click',()=>{state.settings.startDate=document.getElementById('start-date').value||state.settings.startDate;state.settings.rest=+document.getElementById('rest-seconds').value;save();renderAll();document.getElementById('settings-sheet').classList.add('hidden')});document.getElementById('save-weight').addEventListener('click',()=>{const v=parseFloat(document.getElementById('weight-input').value);if(!v)return;state.weights.push({date:new Date().toISOString(),value:v});save();document.getElementById('weight-input').value='';renderWeights()});document.getElementById('cal-prev').addEventListener('click',()=>{state.calendarDate.setMonth(state.calendarDate.getMonth()-1);renderCalendar()});document.getElementById('cal-next').addEventListener('click',()=>{state.calendarDate.setMonth(state.calendarDate.getMonth()+1);renderCalendar()});
renderAll();if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));